name: ci
on:
  push:
    branches:
      - $default-branch
    tags:
      - v*
  pull_request:
    branches:
      - $default-branch
  workflow_dispatch: {}
#    Inputs are available under: github.event.inputs.{name}
#    inputs:
#      name:
#        description: 'Variable description'
#        required: true
#        default: 'default value here'
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
jobs:
  # Runs on every push and pull request on the selected branches.
  # Can also be executed manually.
  test:
    name: code quality and correctness
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      # Go
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Prepare runner environment
      - name: Set up runner environment
        run: ./.github/workflows/assets/utils.sh setup
        env:
          GITHUB_USER: ${{ github.actor }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # If "vendor" is in cache, restore.
      # To run conditional steps use:
      # if: steps.vendor-cache.outputs.cache-hit != 'true'
      - name: Restore vendor from cache
        id: vendor-cache
        uses: actions/cache@v2.1.6
        env:
          cache-name: vendor
        with:
          path: ./vendor
          key: ${{ env.cache-name }}-${{ hashFiles('go.sum') }}

      # Style consistency and static analysis using 'golangci-lint'
      # https://github.com/marketplace/actions/run-golangci-lint
      - name: Static analysis
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest

      # Run unit tests
      - name: Test
        run: make test

      # Ensure project compile and build successfully
      - name: Build
        run: make build-for os=linux arch=amd64
      
      # Save artifacts
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path: |
            coverage.html

      # Populate vendor cache to speed up future runs
      - name: Populate vendor cache
        run: go mod vendor
